name: Sync Fork

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2
        with:
          owner: shadow-pen123   # original repo owner
          head: main          # your fork branch
          base: main          # upstream branch
